"""Mock data for IndiaMART AI-Powered RFQ System prototype.

Contains:
- CATEGORY_TAXONOMY: 3-level category hierarchy (L1 > L2 > L3)
- CATEGORY_QUESTIONS: Follow-up question templates per L2 category
- MOCK_SUPPLIERS: 25 supplier profiles across India
- KEYWORD_MAP: Keyword-to-category mapping for classification

In production, these would come from:
- IndiaMART Category API / Taxonomy Service
- Question templates from ML-generated question bank
- Supplier data from ElasticSearch / AlloyDB
"""

# =============================================================================
# CATEGORY TAXONOMY
# Maps L1 -> L2 -> [L3 categories]
# Each L3 has an auto-generated category_id
# =============================================================================

CATEGORY_TAXONOMY: dict[str, dict[str, list[str]]] = {
    "Industrial Machinery": {
        "Packaging Machinery": [
            "Form Fill Seal (FFS)",
            "Flow Wrap Machine",
            "Shrink Wrap Machine",
            "Vacuum Packaging Machine",
            "Pouch Packing Machine",
            "Bottle Filling Machine",
        ],
        "CNC Machines": [
            "CNC Lathe",
            "CNC Milling Machine",
            "CNC Router",
            "CNC Plasma Cutter",
            "CNC Grinding Machine",
        ],
        "Printing Machinery": [
            "Flexographic Printing Machine",
            "Offset Printing Machine",
            "Digital Printing Machine",
            "Screen Printing Machine",
        ],
        "Food Processing Machinery": [
            "Flour Mill",
            "Oil Extraction Machine",
            "Spice Grinding Machine",
            "Bakery Equipment",
        ],
    },
    "Textiles & Apparel": {
        "Fabrics": [
            "Cotton Fabric",
            "Polyester Fabric",
            "Silk Fabric",
            "Denim",
            "Linen Fabric",
            "Rayon Fabric",
        ],
        "Garments": [
            "T-Shirts",
            "Uniforms",
            "Ethnic Wear",
            "Corporate Shirts",
            "Sports Wear",
        ],
        "Textile Machinery": [
            "Weaving Loom",
            "Knitting Machine",
            "Embroidery Machine",
            "Dyeing Machine",
        ],
    },
    "Furniture": {
        "Commercial Furniture": [
            "Restaurant Chairs",
            "Office Chairs",
            "Cafeteria Tables",
            "Reception Desks",
            "Conference Tables",
        ],
        "Home Furniture": [
            "Sofa Sets",
            "Beds",
            "Dining Tables",
            "Wardrobes",
            "TV Units",
        ],
        "School & Institutional": [
            "School Desks",
            "Library Furniture",
            "Lab Furniture",
            "Hostel Furniture",
        ],
    },
    "Chemicals": {
        "Industrial Chemicals": [
            "Solvents",
            "Adhesives",
            "Lubricants",
            "Cleaning Agents",
            "Water Treatment Chemicals",
        ],
        "Specialty Chemicals": [
            "Pigments & Dyes",
            "Flame Retardants",
            "Plasticizers",
            "Catalysts",
        ],
    },
    "Electronics & Electrical": {
        "Electronic Components": [
            "PCBs",
            "Capacitors",
            "Connectors",
            "Resistors",
            "Transformers",
        ],
        "Electrical Equipment": [
            "Switchgear",
            "Distribution Panels",
            "UPS Systems",
            "Solar Panels",
            "LED Lights",
        ],
    },
    "Building & Construction": {
        "Construction Materials": [
            "Cement",
            "TMT Steel Bars",
            "Bricks",
            "Sand",
            "Ready Mix Concrete",
        ],
        "Plumbing & Sanitary": [
            "PVC Pipes",
            "Water Tanks",
            "Bathroom Fittings",
            "Pumps",
        ],
    },
}


# =============================================================================
# KEYWORD MAP
# Maps common keywords/phrases to (L1, L2) tuples for classification
# Includes Hindi/Hinglish keywords
# =============================================================================

KEYWORD_MAP: dict[str, tuple[str, str]] = {
    # Packaging Machinery
    "packaging machine": ("Industrial Machinery", "Packaging Machinery"),
    "packing machine": ("Industrial Machinery", "Packaging Machinery"),
    "ffs machine": ("Industrial Machinery", "Packaging Machinery"),
    "form fill seal": ("Industrial Machinery", "Packaging Machinery"),
    "flow wrap": ("Industrial Machinery", "Packaging Machinery"),
    "shrink wrap": ("Industrial Machinery", "Packaging Machinery"),
    "vacuum packaging": ("Industrial Machinery", "Packaging Machinery"),
    "pouch packing": ("Industrial Machinery", "Packaging Machinery"),
    "bottle filling": ("Industrial Machinery", "Packaging Machinery"),
    "namkeen packing": ("Industrial Machinery", "Packaging Machinery"),
    "chips packing": ("Industrial Machinery", "Packaging Machinery"),
    "masala packing": ("Industrial Machinery", "Packaging Machinery"),
    # CNC Machines
    "cnc": ("Industrial Machinery", "CNC Machines"),
    "cnc lathe": ("Industrial Machinery", "CNC Machines"),
    "cnc milling": ("Industrial Machinery", "CNC Machines"),
    "cnc router": ("Industrial Machinery", "CNC Machines"),
    "cnc machine": ("Industrial Machinery", "CNC Machines"),
    # Printing
    "printing machine": ("Industrial Machinery", "Printing Machinery"),
    "flexo": ("Industrial Machinery", "Printing Machinery"),
    "offset printing": ("Industrial Machinery", "Printing Machinery"),
    # Food Processing
    "flour mill": ("Industrial Machinery", "Food Processing Machinery"),
    "atta chakki": ("Industrial Machinery", "Food Processing Machinery"),
    "oil extraction": ("Industrial Machinery", "Food Processing Machinery"),
    "food processing": ("Industrial Machinery", "Food Processing Machinery"),
    "spice grinding": ("Industrial Machinery", "Food Processing Machinery"),
    # Fabrics
    "fabric": ("Textiles & Apparel", "Fabrics"),
    "cotton": ("Textiles & Apparel", "Fabrics"),
    "polyester": ("Textiles & Apparel", "Fabrics"),
    "silk": ("Textiles & Apparel", "Fabrics"),
    "denim": ("Textiles & Apparel", "Fabrics"),
    "kapda": ("Textiles & Apparel", "Fabrics"),
    "cloth": ("Textiles & Apparel", "Fabrics"),
    # Garments
    "t-shirt": ("Textiles & Apparel", "Garments"),
    "tshirt": ("Textiles & Apparel", "Garments"),
    "uniform": ("Textiles & Apparel", "Garments"),
    "ethnic wear": ("Textiles & Apparel", "Garments"),
    "kurta": ("Textiles & Apparel", "Garments"),
    "corporate shirt": ("Textiles & Apparel", "Garments"),
    # Commercial Furniture
    "restaurant chair": ("Furniture", "Commercial Furniture"),
    "office chair": ("Furniture", "Commercial Furniture"),
    "cafeteria table": ("Furniture", "Commercial Furniture"),
    "conference table": ("Furniture", "Commercial Furniture"),
    "office furniture": ("Furniture", "Commercial Furniture"),
    "commercial furniture": ("Furniture", "Commercial Furniture"),
    # Home Furniture
    "sofa": ("Furniture", "Home Furniture"),
    "bed": ("Furniture", "Home Furniture"),
    "dining table": ("Furniture", "Home Furniture"),
    "wardrobe": ("Furniture", "Home Furniture"),
    "furniture": ("Furniture", "Home Furniture"),
    # School Furniture
    "school desk": ("Furniture", "School & Institutional"),
    "school furniture": ("Furniture", "School & Institutional"),
    "lab furniture": ("Furniture", "School & Institutional"),
    # Chemicals
    "solvent": ("Chemicals", "Industrial Chemicals"),
    "adhesive": ("Chemicals", "Industrial Chemicals"),
    "lubricant": ("Chemicals", "Industrial Chemicals"),
    "chemical": ("Chemicals", "Industrial Chemicals"),
    "cleaning agent": ("Chemicals", "Industrial Chemicals"),
    # Electronics
    "pcb": ("Electronics & Electrical", "Electronic Components"),
    "capacitor": ("Electronics & Electrical", "Electronic Components"),
    "connector": ("Electronics & Electrical", "Electronic Components"),
    "electronic component": ("Electronics & Electrical", "Electronic Components"),
    # Electrical
    "switchgear": ("Electronics & Electrical", "Electrical Equipment"),
    "solar panel": ("Electronics & Electrical", "Electrical Equipment"),
    "led light": ("Electronics & Electrical", "Electrical Equipment"),
    "ups": ("Electronics & Electrical", "Electrical Equipment"),
    # Construction
    "cement": ("Building & Construction", "Construction Materials"),
    "tmt bar": ("Building & Construction", "Construction Materials"),
    "steel bar": ("Building & Construction", "Construction Materials"),
    "brick": ("Building & Construction", "Construction Materials"),
    # Plumbing
    "pvc pipe": ("Building & Construction", "Plumbing & Sanitary"),
    "water tank": ("Building & Construction", "Plumbing & Sanitary"),
    "pump": ("Building & Construction", "Plumbing & Sanitary"),
    "bathroom fitting": ("Building & Construction", "Plumbing & Sanitary"),
}


# =============================================================================
# CATEGORY QUESTIONS
# Follow-up question templates per L2 category
# Each question: field_name, question_en, question_hi, options, priority, priority_score
# =============================================================================

CATEGORY_QUESTIONS: dict[str, list[dict]] = {
    "Packaging Machinery": [
        {
            "field_name": "machine_type",
            "question_en": "What type of packaging machine do you need?",
            "question_hi": "Aapko kis tarah ki packaging machine chahiye?",
            "options": [
                "Form Fill Seal (FFS)",
                "Flow Wrap",
                "Shrink Wrap",
                "Vacuum Packaging",
                "Pouch Packing",
                "Bottle Filling",
                "Other",
            ],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "product_to_pack",
            "question_en": "What product will you be packaging?",
            "question_hi": "Aap kya pack karna chahte hain?",
            "options": [],
            "priority": "P0",
            "priority_score": 0.92,
        },
        {
            "field_name": "automation_level",
            "question_en": "Do you need automatic or semi-automatic?",
            "question_hi": "Automatic chahiye ya semi-automatic?",
            "options": ["Fully Automatic", "Semi-Automatic", "Manual"],
            "priority": "P0",
            "priority_score": 0.88,
        },
        {
            "field_name": "throughput",
            "question_en": "How many packs per minute do you need?",
            "question_hi": "Ek minute mein kitne packs chahiye?",
            "options": ["10-20", "20-40", "40-60", "60-100", "100+"],
            "priority": "P1",
            "priority_score": 0.80,
        },
        {
            "field_name": "pack_size",
            "question_en": "What pack sizes do you need? (e.g., 50g, 100g, 500g, 1kg)",
            "question_hi": "Kitne gram/kg ke pack chahiye?",
            "options": ["50g or less", "50g-200g", "200g-500g", "500g-1kg", "Above 1kg"],
            "priority": "P1",
            "priority_score": 0.76,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your approximate budget?",
            "question_hi": "Aapka budget kitna hai (lagbhag)?",
            "options": ["Under 5 Lakh", "5-15 Lakh", "15-30 Lakh", "Above 30 Lakh"],
            "priority": "P1",
            "priority_score": 0.75,
        },
    ],
    "CNC Machines": [
        {
            "field_name": "cnc_type",
            "question_en": "What type of CNC machine are you looking for?",
            "question_hi": "Kis tarah ki CNC machine chahiye?",
            "options": ["CNC Lathe", "CNC Milling", "CNC Router", "CNC Plasma Cutter", "CNC Grinding"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "material_to_work",
            "question_en": "What material will you be machining?",
            "question_hi": "Kaunsa material machine karna hai?",
            "options": ["Mild Steel", "Stainless Steel", "Aluminum", "Brass/Copper", "Wood", "Plastic", "Other"],
            "priority": "P0",
            "priority_score": 0.90,
        },
        {
            "field_name": "axis_count",
            "question_en": "How many axes do you need?",
            "question_hi": "Kitne axis ki machine chahiye?",
            "options": ["2-Axis", "3-Axis", "4-Axis", "5-Axis"],
            "priority": "P0",
            "priority_score": 0.88,
        },
        {
            "field_name": "work_envelope",
            "question_en": "What is the maximum workpiece size (mm)?",
            "question_hi": "Sabse bada workpiece kitna hoga (mm)?",
            "options": [],
            "priority": "P1",
            "priority_score": 0.78,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your approximate budget?",
            "question_hi": "Aapka budget kitna hai?",
            "options": ["Under 10 Lakh", "10-25 Lakh", "25-50 Lakh", "50 Lakh-1 Crore", "Above 1 Crore"],
            "priority": "P1",
            "priority_score": 0.75,
        },
    ],
    "Fabrics": [
        {
            "field_name": "fabric_type",
            "question_en": "What type of fabric do you need?",
            "question_hi": "Kaunsa fabric chahiye?",
            "options": ["Cotton", "Polyester", "Silk", "Denim", "Linen", "Rayon", "Blended", "Other"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "usage_purpose",
            "question_en": "What is the fabric for? (garments, upholstery, industrial, etc.)",
            "question_hi": "Fabric ka use kya hoga? (kapde, furniture, industrial)",
            "options": ["Garments/Apparel", "Upholstery", "Industrial Use", "Home Furnishing", "Export", "Other"],
            "priority": "P0",
            "priority_score": 0.92,
        },
        {
            "field_name": "gsm_weight",
            "question_en": "What GSM (weight) do you need?",
            "question_hi": "Kitne GSM ka fabric chahiye?",
            "options": ["Light (below 150 GSM)", "Medium (150-250 GSM)", "Heavy (above 250 GSM)"],
            "priority": "P0",
            "priority_score": 0.85,
        },
        {
            "field_name": "quantity",
            "question_en": "How much fabric do you need? (in meters or kg)",
            "question_hi": "Kitna fabric chahiye? (meter ya kg mein)",
            "options": [],
            "priority": "P1",
            "priority_score": 0.80,
        },
        {
            "field_name": "color_pattern",
            "question_en": "Do you need a specific color or pattern?",
            "question_hi": "Koi specific color ya pattern chahiye?",
            "options": ["Solid/Plain", "Printed", "Dyed", "Check/Stripe", "Custom Print"],
            "priority": "P1",
            "priority_score": 0.70,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your budget per meter/kg?",
            "question_hi": "Per meter/kg ka budget kitna hai?",
            "options": ["Under Rs 50/m", "Rs 50-150/m", "Rs 150-300/m", "Above Rs 300/m"],
            "priority": "P2",
            "priority_score": 0.65,
        },
    ],
    "Garments": [
        {
            "field_name": "garment_type",
            "question_en": "What type of garment do you need?",
            "question_hi": "Kaunsa garment chahiye?",
            "options": ["T-Shirts", "Uniforms", "Ethnic Wear", "Corporate Shirts", "Sports Wear", "Other"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "quantity",
            "question_en": "How many pieces do you need?",
            "question_hi": "Kitne pieces chahiye?",
            "options": ["50-100", "100-500", "500-1000", "1000-5000", "5000+"],
            "priority": "P0",
            "priority_score": 0.90,
        },
        {
            "field_name": "fabric_preference",
            "question_en": "Any fabric preference?",
            "question_hi": "Koi fabric preference hai?",
            "options": ["Cotton", "Polyester", "Cotton-Poly Blend", "Dry-Fit", "No Preference"],
            "priority": "P1",
            "priority_score": 0.80,
        },
        {
            "field_name": "customization",
            "question_en": "Do you need printing/embroidery (logo, name, etc.)?",
            "question_hi": "Printing ya embroidery chahiye (logo, naam, etc.)?",
            "options": ["Screen Printing", "Embroidery", "Digital Printing", "Plain (no printing)", "Other"],
            "priority": "P1",
            "priority_score": 0.78,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your budget per piece?",
            "question_hi": "Per piece ka budget kitna hai?",
            "options": ["Under Rs 100", "Rs 100-250", "Rs 250-500", "Above Rs 500"],
            "priority": "P1",
            "priority_score": 0.72,
        },
    ],
    "Commercial Furniture": [
        {
            "field_name": "furniture_type",
            "question_en": "What type of commercial furniture do you need?",
            "question_hi": "Kaunsa commercial furniture chahiye?",
            "options": ["Restaurant Chairs", "Office Chairs", "Cafeteria Tables", "Reception Desks", "Conference Tables", "Other"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "material",
            "question_en": "What material do you prefer?",
            "question_hi": "Kaunsa material pasand hai?",
            "options": ["Wood", "Metal/Steel", "Plastic/Polypropylene", "Combination", "No Preference"],
            "priority": "P0",
            "priority_score": 0.88,
        },
        {
            "field_name": "quantity",
            "question_en": "How many pieces do you need?",
            "question_hi": "Kitne pieces chahiye?",
            "options": ["1-10", "10-50", "50-100", "100-500", "500+"],
            "priority": "P0",
            "priority_score": 0.85,
        },
        {
            "field_name": "usage_location",
            "question_en": "Where will this be used? (restaurant, office, outdoor, etc.)",
            "question_hi": "Kahan use hoga? (restaurant, office, outdoor)",
            "options": ["Restaurant/Cafe", "Corporate Office", "Outdoor", "Hotel/Banquet", "Hospital", "Other"],
            "priority": "P1",
            "priority_score": 0.78,
        },
        {
            "field_name": "customization",
            "question_en": "Do you need any customization (color, logo, size)?",
            "question_hi": "Koi customization chahiye (color, logo, size)?",
            "options": [],
            "priority": "P2",
            "priority_score": 0.65,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your budget per piece?",
            "question_hi": "Per piece ka budget kitna hai?",
            "options": ["Under Rs 1,000", "Rs 1,000-3,000", "Rs 3,000-5,000", "Rs 5,000-10,000", "Above Rs 10,000"],
            "priority": "P1",
            "priority_score": 0.72,
        },
    ],
    "Home Furniture": [
        {
            "field_name": "furniture_type",
            "question_en": "What type of home furniture do you need?",
            "question_hi": "Ghar ke liye kaunsa furniture chahiye?",
            "options": ["Sofa Set", "Bed", "Dining Table Set", "Wardrobe", "TV Unit", "Other"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "material",
            "question_en": "What material do you prefer?",
            "question_hi": "Kaunsa material pasand hai?",
            "options": ["Sheesham Wood", "Teak Wood", "Engineered Wood/MDF", "Metal", "Upholstered", "No Preference"],
            "priority": "P0",
            "priority_score": 0.88,
        },
        {
            "field_name": "size",
            "question_en": "What size do you need?",
            "question_hi": "Kya size chahiye?",
            "options": [],
            "priority": "P1",
            "priority_score": 0.80,
        },
        {
            "field_name": "quantity",
            "question_en": "How many pieces do you need?",
            "question_hi": "Kitne pieces chahiye?",
            "options": ["1", "2-5", "5-10", "10+"],
            "priority": "P1",
            "priority_score": 0.75,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your approximate budget?",
            "question_hi": "Aapka budget kitna hai?",
            "options": ["Under Rs 10,000", "Rs 10,000-25,000", "Rs 25,000-50,000", "Above Rs 50,000"],
            "priority": "P1",
            "priority_score": 0.72,
        },
    ],
    "Industrial Chemicals": [
        {
            "field_name": "chemical_type",
            "question_en": "What type of chemical do you need?",
            "question_hi": "Kaunsa chemical chahiye?",
            "options": ["Solvents", "Adhesives", "Lubricants", "Cleaning Agents", "Water Treatment", "Other"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "application",
            "question_en": "What is the application/industry?",
            "question_hi": "Kis kaam ke liye chahiye?",
            "options": ["Manufacturing", "Construction", "Automotive", "Food Grade", "Pharmaceutical", "Other"],
            "priority": "P0",
            "priority_score": 0.90,
        },
        {
            "field_name": "quantity",
            "question_en": "How much quantity do you need? (in litres or kg)",
            "question_hi": "Kitni quantity chahiye? (litre ya kg)",
            "options": [],
            "priority": "P0",
            "priority_score": 0.85,
        },
        {
            "field_name": "purity_grade",
            "question_en": "What purity/grade do you need?",
            "question_hi": "Kaunsa grade chahiye?",
            "options": ["Technical Grade", "LR Grade", "AR Grade", "Food Grade", "Any"],
            "priority": "P1",
            "priority_score": 0.78,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your budget per kg/litre?",
            "question_hi": "Per kg/litre ka budget kitna hai?",
            "options": [],
            "priority": "P2",
            "priority_score": 0.65,
        },
    ],
    "Electronic Components": [
        {
            "field_name": "component_type",
            "question_en": "What electronic component do you need?",
            "question_hi": "Kaunsa electronic component chahiye?",
            "options": ["PCBs", "Capacitors", "Connectors", "Resistors", "Transformers", "ICs", "Other"],
            "priority": "P0",
            "priority_score": 0.95,
        },
        {
            "field_name": "specifications",
            "question_en": "What are the technical specifications? (value, voltage, size, etc.)",
            "question_hi": "Technical specifications kya hain?",
            "options": [],
            "priority": "P0",
            "priority_score": 0.90,
        },
        {
            "field_name": "quantity",
            "question_en": "How many pieces do you need?",
            "question_hi": "Kitne pieces chahiye?",
            "options": ["1-100", "100-1000", "1000-10000", "10000+"],
            "priority": "P0",
            "priority_score": 0.85,
        },
        {
            "field_name": "application",
            "question_en": "What is the application?",
            "question_hi": "Kis project/product ke liye chahiye?",
            "options": [],
            "priority": "P1",
            "priority_score": 0.75,
        },
        {
            "field_name": "budget_range",
            "question_en": "What is your budget per piece/lot?",
            "question_hi": "Per piece ya lot ka budget?",
            "options": [],
            "priority": "P2",
            "priority_score": 0.65,
        },
    ],
}


# =============================================================================
# MOCK SUPPLIERS DATABASE
# 25 suppliers across various categories and Indian cities
# =============================================================================

MOCK_SUPPLIERS: list[dict] = [
    # --- Packaging Machinery Suppliers ---
    {
        "supplier_id": "SUP-001",
        "company_name": "PackTech Solutions Pvt. Ltd.",
        "location": "Noida",
        "state": "Uttar Pradesh",
        "categories": ["Packaging Machinery"],
        "products": [
            "Form Fill Seal Machine",
            "Pouch Packing Machine",
            "Automatic FFS Machine",
            "Nitrogen Flushing Machine",
        ],
        "trust_seal": True,
        "member_since": 2012,
        "response_rate": 0.92,
        "price_range": "3 Lakh - 25 Lakh",
    },
    {
        "supplier_id": "SUP-002",
        "company_name": "AutoPack Industries",
        "location": "Pune",
        "state": "Maharashtra",
        "categories": ["Packaging Machinery"],
        "products": [
            "Flow Wrap Machine",
            "Shrink Wrap Machine",
            "Horizontal FFS Machine",
            "Multi-Head Weigher",
        ],
        "trust_seal": True,
        "member_since": 2015,
        "response_rate": 0.88,
        "price_range": "5 Lakh - 35 Lakh",
    },
    {
        "supplier_id": "SUP-003",
        "company_name": "Shree Balaji Packaging",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "categories": ["Packaging Machinery"],
        "products": [
            "Pouch Packing Machine",
            "Semi-Automatic FFS",
            "Cup Filling Machine",
            "Granule Packing Machine",
        ],
        "trust_seal": False,
        "member_since": 2018,
        "response_rate": 0.75,
        "price_range": "1.5 Lakh - 15 Lakh",
    },
    {
        "supplier_id": "SUP-004",
        "company_name": "Sai Engineers",
        "location": "Mumbai",
        "state": "Maharashtra",
        "categories": ["Packaging Machinery", "Food Processing Machinery"],
        "products": [
            "Vacuum Packaging Machine",
            "Bottle Filling Line",
            "Capping Machine",
            "Labeling Machine",
        ],
        "trust_seal": True,
        "member_since": 2010,
        "response_rate": 0.95,
        "price_range": "2 Lakh - 40 Lakh",
    },
    # --- CNC Machine Suppliers ---
    {
        "supplier_id": "SUP-005",
        "company_name": "Precision CNC Technologies",
        "location": "Pune",
        "state": "Maharashtra",
        "categories": ["CNC Machines"],
        "products": [
            "CNC Lathe Machine",
            "CNC Turning Center",
            "CNC Milling Machine",
            "VMC Machine",
        ],
        "trust_seal": True,
        "member_since": 2011,
        "response_rate": 0.90,
        "price_range": "8 Lakh - 1.2 Crore",
    },
    {
        "supplier_id": "SUP-006",
        "company_name": "Bharat Machine Tools",
        "location": "Coimbatore",
        "state": "Tamil Nadu",
        "categories": ["CNC Machines"],
        "products": [
            "CNC Lathe",
            "CNC Router",
            "CNC Plasma Cutter",
            "Conventional Lathe",
        ],
        "trust_seal": True,
        "member_since": 2008,
        "response_rate": 0.87,
        "price_range": "5 Lakh - 80 Lakh",
    },
    {
        "supplier_id": "SUP-007",
        "company_name": "Excel CNC Systems",
        "location": "Rajkot",
        "state": "Gujarat",
        "categories": ["CNC Machines"],
        "products": [
            "CNC Milling Machine",
            "CNC Grinding Machine",
            "CNC Drilling Machine",
        ],
        "trust_seal": False,
        "member_since": 2016,
        "response_rate": 0.78,
        "price_range": "6 Lakh - 60 Lakh",
    },
    # --- Fabric / Textile Suppliers ---
    {
        "supplier_id": "SUP-008",
        "company_name": "Arvind Textiles",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "categories": ["Fabrics", "Garments"],
        "products": [
            "Cotton Fabric",
            "Denim Fabric",
            "Shirting Fabric",
            "Suiting Fabric",
        ],
        "trust_seal": True,
        "member_since": 2009,
        "response_rate": 0.93,
        "price_range": "Rs 40 - Rs 350 per meter",
    },
    {
        "supplier_id": "SUP-009",
        "company_name": "Ludhiana Fabric House",
        "location": "Ludhiana",
        "state": "Punjab",
        "categories": ["Fabrics"],
        "products": [
            "Polyester Fabric",
            "Rayon Fabric",
            "Velvet Fabric",
            "Knitted Fabric",
        ],
        "trust_seal": False,
        "member_since": 2017,
        "response_rate": 0.72,
        "price_range": "Rs 30 - Rs 250 per meter",
    },
    {
        "supplier_id": "SUP-010",
        "company_name": "Silk Road Traders",
        "location": "Varanasi",
        "state": "Uttar Pradesh",
        "categories": ["Fabrics"],
        "products": [
            "Silk Fabric",
            "Banarasi Silk",
            "Organza",
            "Chanderi Silk",
        ],
        "trust_seal": True,
        "member_since": 2013,
        "response_rate": 0.85,
        "price_range": "Rs 200 - Rs 2,500 per meter",
    },
    # --- Garment Suppliers ---
    {
        "supplier_id": "SUP-011",
        "company_name": "Tirupur Garments Co.",
        "location": "Coimbatore",
        "state": "Tamil Nadu",
        "categories": ["Garments"],
        "products": [
            "T-Shirts",
            "Polo T-Shirts",
            "Sports Wear",
            "Promotional T-Shirts",
        ],
        "trust_seal": True,
        "member_since": 2010,
        "response_rate": 0.91,
        "price_range": "Rs 80 - Rs 450 per piece",
    },
    {
        "supplier_id": "SUP-012",
        "company_name": "National Uniform Company",
        "location": "Delhi",
        "state": "Delhi",
        "categories": ["Garments"],
        "products": [
            "School Uniforms",
            "Industrial Uniforms",
            "Security Uniforms",
            "Corporate Shirts",
        ],
        "trust_seal": True,
        "member_since": 2014,
        "response_rate": 0.86,
        "price_range": "Rs 150 - Rs 800 per piece",
    },
    # --- Commercial Furniture Suppliers ---
    {
        "supplier_id": "SUP-013",
        "company_name": "Steel Craft Furniture",
        "location": "Mumbai",
        "state": "Maharashtra",
        "categories": ["Commercial Furniture"],
        "products": [
            "Restaurant Chairs",
            "Cafeteria Tables",
            "Bar Stools",
            "Banquet Chairs",
        ],
        "trust_seal": True,
        "member_since": 2011,
        "response_rate": 0.89,
        "price_range": "Rs 800 - Rs 8,000 per piece",
    },
    {
        "supplier_id": "SUP-014",
        "company_name": "Ergonomic Office Solutions",
        "location": "Noida",
        "state": "Uttar Pradesh",
        "categories": ["Commercial Furniture"],
        "products": [
            "Office Chairs",
            "Executive Chairs",
            "Conference Tables",
            "Reception Desks",
            "Workstations",
        ],
        "trust_seal": True,
        "member_since": 2013,
        "response_rate": 0.91,
        "price_range": "Rs 2,000 - Rs 25,000 per piece",
    },
    {
        "supplier_id": "SUP-015",
        "company_name": "Rajasthan Furniture Mart",
        "location": "Jodhpur",
        "state": "Rajasthan",
        "categories": ["Commercial Furniture", "Home Furniture"],
        "products": [
            "Wooden Chairs",
            "Dining Tables",
            "Sofa Sets",
            "Hotel Furniture",
        ],
        "trust_seal": False,
        "member_since": 2019,
        "response_rate": 0.70,
        "price_range": "Rs 1,500 - Rs 35,000 per piece",
    },
    # --- Home Furniture Suppliers ---
    {
        "supplier_id": "SUP-016",
        "company_name": "Royal Furniture House",
        "location": "Delhi",
        "state": "Delhi",
        "categories": ["Home Furniture"],
        "products": [
            "Sofa Sets",
            "King Size Beds",
            "Wardrobes",
            "TV Units",
            "Shoe Racks",
        ],
        "trust_seal": True,
        "member_since": 2012,
        "response_rate": 0.88,
        "price_range": "Rs 5,000 - Rs 1,50,000 per piece",
    },
    {
        "supplier_id": "SUP-017",
        "company_name": "Saharanpur Wood Works",
        "location": "Saharanpur",
        "state": "Uttar Pradesh",
        "categories": ["Home Furniture"],
        "products": [
            "Sheesham Wood Beds",
            "Dining Table Sets",
            "Wooden Sofa",
            "Dressing Tables",
        ],
        "trust_seal": False,
        "member_since": 2016,
        "response_rate": 0.74,
        "price_range": "Rs 8,000 - Rs 80,000 per piece",
    },
    # --- Chemical Suppliers ---
    {
        "supplier_id": "SUP-018",
        "company_name": "ChemPure Industries",
        "location": "Mumbai",
        "state": "Maharashtra",
        "categories": ["Industrial Chemicals"],
        "products": [
            "Solvents",
            "Thinners",
            "Acetone",
            "Isopropyl Alcohol",
            "Toluene",
        ],
        "trust_seal": True,
        "member_since": 2010,
        "response_rate": 0.90,
        "price_range": "Rs 50 - Rs 500 per litre",
    },
    {
        "supplier_id": "SUP-019",
        "company_name": "BondTech Adhesives",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "categories": ["Industrial Chemicals"],
        "products": [
            "Industrial Adhesives",
            "Epoxy Resins",
            "PVA Glue",
            "Hot Melt Adhesive",
        ],
        "trust_seal": True,
        "member_since": 2014,
        "response_rate": 0.84,
        "price_range": "Rs 100 - Rs 1,200 per kg",
    },
    # --- Electronics Suppliers ---
    {
        "supplier_id": "SUP-020",
        "company_name": "MicroTech Components",
        "location": "Delhi",
        "state": "Delhi",
        "categories": ["Electronic Components"],
        "products": [
            "PCBs",
            "Custom PCB",
            "Multilayer PCB",
            "Flex PCB",
        ],
        "trust_seal": True,
        "member_since": 2012,
        "response_rate": 0.88,
        "price_range": "Rs 5 - Rs 2,000 per piece",
    },
    {
        "supplier_id": "SUP-021",
        "company_name": "National Capacitors Ltd.",
        "location": "Pune",
        "state": "Maharashtra",
        "categories": ["Electronic Components"],
        "products": [
            "Electrolytic Capacitors",
            "Ceramic Capacitors",
            "Film Capacitors",
            "Connectors",
        ],
        "trust_seal": True,
        "member_since": 2009,
        "response_rate": 0.92,
        "price_range": "Rs 1 - Rs 500 per piece",
    },
    # --- Electrical Equipment Suppliers ---
    {
        "supplier_id": "SUP-022",
        "company_name": "PowerGrid Solutions",
        "location": "Noida",
        "state": "Uttar Pradesh",
        "categories": ["Electrical Equipment"],
        "products": [
            "Switchgear",
            "Distribution Panels",
            "UPS Systems",
            "Stabilizers",
        ],
        "trust_seal": True,
        "member_since": 2011,
        "response_rate": 0.87,
        "price_range": "Rs 5,000 - Rs 5,00,000",
    },
    # --- Construction Suppliers ---
    {
        "supplier_id": "SUP-023",
        "company_name": "BuildRight Materials",
        "location": "Delhi",
        "state": "Delhi",
        "categories": ["Construction Materials"],
        "products": [
            "TMT Steel Bars",
            "Cement",
            "Ready Mix Concrete",
            "AAC Blocks",
        ],
        "trust_seal": True,
        "member_since": 2013,
        "response_rate": 0.85,
        "price_range": "Varies by material",
    },
    {
        "supplier_id": "SUP-024",
        "company_name": "Jain Plumbing & Sanitary",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "categories": ["Plumbing & Sanitary"],
        "products": [
            "PVC Pipes",
            "CPVC Pipes",
            "Water Tanks",
            "Bathroom Fittings",
            "Pumps",
        ],
        "trust_seal": False,
        "member_since": 2017,
        "response_rate": 0.76,
        "price_range": "Rs 100 - Rs 50,000",
    },
    {
        "supplier_id": "SUP-025",
        "company_name": "South India Machines",
        "location": "Coimbatore",
        "state": "Tamil Nadu",
        "categories": ["Packaging Machinery", "Food Processing Machinery"],
        "products": [
            "Pouch Packing Machine",
            "Flour Mill",
            "Oil Extraction Machine",
            "Spice Grinding Machine",
        ],
        "trust_seal": True,
        "member_since": 2014,
        "response_rate": 0.83,
        "price_range": "2 Lakh - 20 Lakh",
    },
]


# =============================================================================
# STATE / CITY MAPPING (for location-based scoring)
# =============================================================================

CITY_STATE_MAP: dict[str, str] = {
    "noida": "Uttar Pradesh",
    "delhi": "Delhi",
    "new delhi": "Delhi",
    "mumbai": "Maharashtra",
    "pune": "Maharashtra",
    "ahmedabad": "Gujarat",
    "rajkot": "Gujarat",
    "coimbatore": "Tamil Nadu",
    "chennai": "Tamil Nadu",
    "ludhiana": "Punjab",
    "varanasi": "Uttar Pradesh",
    "jodhpur": "Rajasthan",
    "jaipur": "Rajasthan",
    "saharanpur": "Uttar Pradesh",
    "kolkata": "West Bengal",
    "hyderabad": "Telangana",
    "bangalore": "Karnataka",
    "bengaluru": "Karnataka",
}
